server:
  port: 8080

spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://mysql-0.sanchar.cn:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=yes
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        slave:
          url: jdbc:mysql://mysql-0.sanchar.cn:3306/test-1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=yes
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver
        mysql:
          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false}
          username: ${SPRING_DATASOURCE_USERNAME:hzero}
          password: ${SPRING_DATASOURCE_PASSWORD:hzero}
          driver-class-name: com.mysql.jdbc.Driver
        #          hikari:
        #            # 连接池最小空闲连接数
        #            minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
        #            # 连接池允许的最大连接数
        #            maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
        #            # 等待连接池分配连接的最大时长（毫秒）
        #            connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
        oracle:
          jdbc-url: jdbc:oracle:thin:@199.20.21.166:1522:TEST
          username: apps
          password: test2009
          driver-class-name: oracle.jdbc.driver.OracleDriver
      durid:
        initial-size: 1
        max-active: 20
        min-idle: 1
        max-wait: 60000
  autoconfigure:
    exclude:  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure # 去除druid配置

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: per.san.domain

#showSql
logging:
  level:
    per.san.mapper: debug